version: '3.9'

services:
    api:
        container_name: api
        build:
            context: ./backend
            dockerfile: Dockerfile
            args:
                - API_PORT=${API_PORT}
        restart: unless-stopped
        env_file: .env
        ports:
            - '${API_PORT}:${API_PORT}'
        depends_on:
            - mongo
        volumes:
            - ./backend:/app

    application:
        container_name: application
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                - FRONTEND_PORT=${FRONTEND_PORT}
        restart: unless-stopped
        env_file: .env
        ports:
            - '${FRONTEND_PORT}:${FRONTEND_PORT}'
        volumes:
            - ./frontend:/app

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        env_file: .env
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - dbdata:/data/db

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        env_file: .env
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin

    robot-go:
        container_name: robot
        env_file: .env
        build:
            context: ./robot
            dockerfile: Dockerfile
            args:
                - ROBOT_PORT=${ROBOT_PORT}
        ports:
            - '${ROBOT_PORT}:${ROBOT_PORT}'
        volumes:
            - ./robot:/app

volumes:
    dbdata:
