version: '3.9'

services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - API_PORT=${API_PORT}
        restart: unless-stopped
        ports:
            - '${API_PORT}:${API_PORT}'
        depends_on:
            - mongo
        volumes:
            - .:/app

    mongo:
        container_name: mongo
        image: mongo
        restart: always
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - dbdata:/data/db

    mongo-express:
        container_name: mongo-express
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        links:
            - mongo
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
            ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin

volumes:
    dbdata:
